version: '3.1'
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRESQL_USER}
      - POSTGRES_USER=${POSTGRESQL_PASSWORD}
      - POSTGRES_DB=${POSTGRESQL_DATABASE}
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8181:8080
    
  jenkins:
    image: jenkins/jenkins
    volumes:
      - jenkins_data:/jenkins_config
    ports:
      - 8080:8080
      - 50000:50000

  mlflow:
    build:
      context: ./docker_files
      dockerfile: Dockerfile
    container_name: mlflow
    expose:
      - "5000"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    command: mlflow server --backend-store-uri postgresql://${POSTGRESQL_USER}:${POSTGRESQL_PASSWORD}@db:5432/${POSTGRESQL_DATABASE} --default-artifact-root s3://mlflow_bucket/mlflow/ --host 0.0.0.0


volumes:
  jenkins_data:
    driver: local
