version: '3.1'
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=test1234
      - POSTGRES_USER=test1234
      - POSTGRES_DB=test1234
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - 8082:8080
      - 50000:50000
    volumes:
      - ~/.aws: /var/jenkins_home/.aws


  mlflow:
    build:
      context: ./docker_files
      dockerfile: Dockerfile
    depends_on:
      - postgres
    container_name: mlflow
    ports:
      - 5000:5000
      - 4040:4040
    volumes:
      - ~/.aws:/root/.aws
    command: mlflow server --backend-store-uri postgresql://test1234:test1234@postgres:5432/test1234 --default-artifact-root s3://mlflow-bucket-bclipp/mlflow/ --host 0.0.0.0


