version: '3.1'
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=test1234
      - POSTGRES_USER=test1234
      - POSTGRES_DB=test1234
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8181:8080
    
  jenkins:
    image: jenkins/jenkins
    volumes:
      - jenkins_data:/jenkins_config
    ports:
      - 8080:8080
      - 50000:50000
volumes:
  jenkins_data:
    driver: local
