pipeline {
    agent any
    stages {
        stage('clean workspace') {
            steps {
                cleanWs()
            }
        }
        stage('Checkout external proj') {
            steps {
                sh "git clone https://github.com/bclipp/mlpipeline_jenkins.git"
            }
        }
        stage("setup env") {
            steps {
                sh 'export PATH="$HOME/.pyenv/bin:$PATH" && \
                eval "$(pyenv init -)" && \
                eval "$(pyenv virtualenv-init -)" && \
                pyenv activate app &&\
                pyenv activate app && \
                python3 --version'
            }
        }
        stage('init db') {
            steps {
                sh ' export PATH="$HOME/.pyenv/bin:$PATH" && \
                eval "$(pyenv init -)" && \
                eval "$(pyenv virtualenv-init -)"&& \
                pyenv activate app &&\
                python3 --version &&\
                python3 mlpipeline_jenkins/app/main.py init_db'
            }
        }
        stage('load one year data on tesla into db') {
            steps {
                sh 'export PATH="$HOME/.pyenv/bin:$PATH" && \
                eval "$(pyenv init -)" && \
                eval "$(pyenv virtualenv-init -)"&& \
                pyenv activate app && \
                 python3 --version &&\
                python3 mlpipeline_jenkins/app/main.py upload_ayear_stock'
            }
        }
        stage('grid search for best GMM model and save in AWS S3') {
            steps {
                sh 'export PATH="$HOME/.pyenv/bin:$PATH" && \
                eval "$(pyenv init -)" && \
                eval "$(pyenv virtualenv-init -)"&& \
                pyenv activate app && \
                 python3 --version &&\
                python3 mlpipeline_jenkins/app/main.py search_train_model'
            }
        }
    }
 }